### ISSUE TITLE
Adding Permalink

### ISSUE THREAD

**Issue by notanewbie** [shadowban-eu/TwitterShadowBanV2#21]
Can you make a permalink feature? That way, people (like me, LOL) can Wayback Machine the page and use it as proof of who's been shadowbanned, or share the page with others, with an example of a shadowbanned user. (For instance, I can send a permalink of http://shadowban.eu?tweeter=getongab and be like "See, they do shadowban people!!!")

**Comment by rbeer** [comment]
Do you know of a way to make those sites wait for a specific signal before capturing?
The testing happens entirely in the frontend as it is now.

If not, this would sadly have to wait for v2 where we'll test in a backend service and serve server-side rendered pages.

**Comment by ghost** [comment]
Note that in order to obtain evidence that an account is shadow banned at a certain point in time, you can manually archive the links that are displayed in the section _Technical information about the result_. In case of QFD, you can simply archive the search link with the quality filter turned off and the search link with the filter turned on.

**Comment by notanewbie** [comment]
Got it, thanks!
