### ISSUE TITLE
Timeouts and error responses

### ISSUE THREAD

**Issue by ghost** [shadowban-eu/TwitterShadowBanV2#7]
Backend failures are currently not handled properly. For example, the search backend might time out. This should be signalled to the user because otherwise, the test appears to be running endlessly. Status codes should be checked as well. Otherwise, the test might return false results instead of displaying an error message to the user.

**Comment by rbeer** [comment]
Proposing extension of proxy script.
I don't know much about PHP, but it should be possible to go more low-level than the current `file_get_contents` approach.

- issue GET request
- discern response (200, 500, 404)
  - return page content on 200
  - otherwise return 500, 404, ... status

Response is checked in [TwitterProxy.checkSuccess](https://github.com/rbeer/TwitterShadowBanV2/blob/master/src/js/twProxy.js#L20-L26), throwing any error status, which is caught by [TwitterProxy.handleError](https://github.com/rbeer/TwitterShadowBanV2/blob/master/src/js/twProxy.js#L40)

@dj95
Do you know of a lib to achieve the PHP part? Minimal client/server functionality would suffice. Don't need a full fledged framework. Current state at [search.php](https://github.com/rbeer/TwitterShadowBanV2/blob/master/src/search.php)

**Comment by rbeer** [comment]
Already solved in #6. My bad.
